import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class COLORS {
  static const Color blackDark = Color(0xff1D1E1F);
  static const Color black = Color(0xff000000);
  static const Color blackMedium = Color(0xff323D5A);
  static const Color blueDark = Color(0xff323D5A);
  static const Color blueLight = Color(0xff687284);
  static const Color blackLight = Color(0xffB0B3C7);
  static const Color checkBox = Color(0xffBCC7CE);
  static const Color greenDark = Color(0xff24734E);
  static const Color greenShade = Color(0x1a24734e);
  static const Color orange = Color(0xffF77223);
  static const Color bluePrimary = Color(0xff013EA3);
  static const Color blueSecondary = Color(0xff1D72DB);
  static const Color blueSecondaryLight = Color(0x801d72db);
  static const Color redDark = Color(0xffD91C30);
  static const Color redMedium = Color(0xffF77223);
  static const Color redShade = Color(0x1af77223);
  static const Color yellow = Color(0xffFBC352);
  static const Color greenLight = Color(0xff50BF97);
  static const Color green = Color(0xff03B15A);
  static const Color whiteBlue = Color(0xffDBE9F2);
  static const Color whiteBlueShade = Color(0x80dbe9f2);
  static const Color whiteBlueLight = Color(0x4ddbe9f2);
  static const Color whiteMedium = Color(0xffBCC7CE);
  static const Color whiteMediumLight = Color(0xffd1d4d5);
  static const Color whiteLight = Color(0xffEDF4F9);
  static const Color divider = Color(0xffDADADA);
  static const Color whiteDark = Color(0xffFFFFFF);
  static const Color shadeBackground = Color(0xffF5F5F5);
  static const Color whiteShade = Color(0xffFAFAFA);
  static const Color whiteLightShade = Color(0xffACBBC5);
  static const Color whiteShare = Color(0xffD9D9D9);
  static const Color whiteCheck = Color(0xffEDF4F9);
  static const Color searchColor = Color(0xff8E99A0);
  static const Color backgroundColor = Color(0xffF3F3F3);
  static const Color backgroundYellowColor = Color(0xffF2AA1B);
  static const Color transparentColor = Color.fromRGBO(255, 0, 0, 0.0);
  static const Color gold = Color(0xffA98056);
  static const Color silver = Color(0xff707070);
  static const Color diamond = Color(0xff69708A);
  static const Color planCard = Color(0xffACBBC5);
  static const Color silverlight = Color(0x323D5A99);
  static const Color brownDark = Color(0xff87929A);
  static const Color silverDark = Color(0xff323D5A);
  static const Color brownLight = Color(0xffACBBC5);
}